import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2e2e2d',
  },
  input: {
    fontSize: 15,
    borderRadius: 50,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 10,
    marginBottom: 5,
    marginTop: 10,
    height: 10,
    borderColor: 'lightgray',
    backgroundColor: 'white',
  },
  link: {
    color: 'lightblue',
  },
  buttonContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 42,
    marginTop: 20,
    borderRadius: 4,
    backgroundColor: '#075E54',
  },
  bg: {
    flex: 1,
  },
  list: {
    padding: 10,
  },
  textContainer: {
    flexDirection: 'row',
    backgroundColor: '#242322',
    alignItems: 'center',
    justifyContent: 'flex-end',
    padding: 5,
  },
  textInput: {
    fontSize: 15,
    backgroundColor: '#2e2e2d',
    flex: 1,
    borderRadius: 50,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'gray',
    padding: 5,
    paddingHorizontal: 10,
    marginHorizontal: 10,
    color: 'white',
  },
  send: {
    backgroundColor: 'royalblue',
    borderRadius: 15,
    overflow: 'hidden',
    padding: 5,
  },
  wrapper: {
    width: '80%',
  },
  signUpInput: {
    fontSize: 15,
    borderRadius: 50,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 10,
    marginBottom: 10,
    height: 30,
    borderColor: 'lightgray',
    backgroundColor: 'white',
  },
  signUpButtonContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 42,
    borderRadius: 4,
    backgroundColor: '#075E54',
  },
  searchContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    backgroundColor: 'black',
  },
  sProfileContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
  },
  profileContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#2e2e2d',
    borderRadius: 10,
    padding: 20,
  },
  imageContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    overflow: 'hidden',
    marginBottom: 20,
  },
  image: {
    flex: 1,
  },
  infoContainer: {
    alignItems: 'center',
  },
  name: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 5,
    color: 'white',
  },
  status: {
    fontSize: 18,
    color: '#777',
  },
  sProfileButtonContainer: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingVertical: 12,
    paddingHorizontal: 42,
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 4,
    backgroundColor: '#075E54',
  },
  profileScreenContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
  },
  eProfileInput: {
    fontSize: 20,
    borderRadius: 50,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 10,
    marginBottom: 5,
    height: 25,
    borderColor: 'lightgray',
    backgroundColor: 'white',
  },
  eChatContainer: {
    flex: 1,
    backgroundColor: 'black',
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  eChatInput: {
    fontSize: 15,
    borderRadius: 50,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 10,
    marginBottom: 10,
    height: 30,
    borderColor: 'lightgray',
    backgroundColor: 'white',
  },
  eChatButtonContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 42,
    borderRadius: 4,
    backgroundColor: '#075E54',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: 400,
    height: 400,
    backgroundColor: '#2e2e2d',
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chatScreenContainer: {
    flex: 1,
    backgroundColor: 'black',
  },
  cameraContainer: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: 'black',
  },
  camera: {
    width: '80%',
    height: '80%',
    aspectRatio: 2,
    justifyContent: 'flex-end',
  },
  subTitle: {
    color: 'grey',
  },
  slItemContainer: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginHorizontal: 15,
    marginVertical: 5,
    height: 70,
    backgroundColor: 'black',
  },
  slContent: {
    flex: 1,
    borderBottomColor: '#232629',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 5,
  },
  msgContainer: {
    margin: 5,
    padding: 10,
    maxWidth: '80%',
    borderRadius: 10,
    alignSelf: 'flex-end',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.18,
    shadowRadius: 4.59,
    elevation: 5,
  },
  time: {
    color: 'gray',
    alignSelf: 'flex-end',
  },
  msgDeleteBox: {
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    marginHorizontal: 15,
    marginVertical: 5,
    borderRadius: 10,
  },
  editText: {
    fontSize: 20,
    marginBottom: 10,
    color: 'white',
  },
  mlDeleteBox: {
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    marginHorizontal: 15,
    marginVertical: 5,
  },
  mlAddBox: {
    backgroundColor: '#075E54',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    marginHorizontal: 15,
    marginVertical: 5,
  },
  mlContainer: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginHorizontal: 15,
    marginVertical: 5,
    height: 70,
    backgroundColor: 'black',
  },
  content: {
    flex: 1,
    borderBottomColor: '#232629',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  mlRow: {
    flexDirection: 'row',
    marginBottom: 5,
  },
  mlName: {
    fontWeight: 'bold',
    flex: 1,
    color: 'white',
  },
  diContainer: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginHorizontal: 15,
    marginVertical: 5,
    height: 70,
    backgroundColor: 'black',
  },
  diSendBox: {
    backgroundColor: 'lightblue',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    marginHorizontal: 15,
    marginVertical: 5,
  },
  editButton: {
    alignContent: 'flex-end',
    alignItems: 'flex-end',
  },
  clname: {
    fontWeight: 'bold',
    flex: 1,
    color: 'white',
  },

});

export default styles;
